# Generated by Django 2.1 on 2019-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='json_text',
            field=models.TextField(blank=True),
        ),
    ]
