# Generated by Django 2.1 on 2019-05-24 14:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_json_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='json_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
