# Generated by Django 2.1 on 2019-05-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190524_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='json_text',
            new_name='text_json',
        ),
    ]
